apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: learningsteps-keyvault
  namespace: learningsteps
spec:
  provider: azure
  secretObjects:
    - secretName: learningsteps-db-secret
      type: Opaque
      data:
        - objectName: learning-steps-secret
          key: POSTGRES_PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: learning-steps-key-vault
    tenantId: "c0531484-50fa-4ff2-97df-b1f2d4810603"
    resourceGroup: "ProjectLearningSteps"
    objects: |
      array:
        - |
          objectName: learning-steps-secret
          objectType: secret
    cloudName: AzurePublicCloud
