apiVersion: v1
kind: Service
metadata:
  name: learningsteps-api
  namespace: learningsteps
spec:
  selector:
    app: learningsteps-api
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer