name: Terraform Static Analysis

on:
  push:
    paths:
      - 'infra-terraform/**'
  pull_request:
    paths:
      - 'infra-terraform/**'

jobs:
  tfsec-checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3.3.0
        with:
          directory: infra-terraform

      - name: Run checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: infra-terraform
